---
- name: Deploiement CliniqueBoreal - Systeme de reservation medicale
  hosts: webservers
  become: yes

  vars:
    db_name: clinique_db
    db_user: clinique_user
    db_password: Boreal2026!

  tasks:
    - name: Mettre a jour apt
      apt:
        update_cache: yes

    - name: Installer Apache2
      apt:
        name: apache2
        state: present

    - name: Installer MySQL
      apt:
        name: mysql-server
        state: present

    - name: Installer PHP et extensions
      apt:
        name:
          - php
          - php-mysql
          - libapache2-mod-php
        state: present

    - name: Installer Python MySQL
      apt:
        name: python3-pymysql
        state: present

    - name: Demarrer MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Demarrer Apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Creer la base de donnees
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creer utilisateur MySQL
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creer table et inserer donnees
      shell: mysql -u root clinique_db < /home/azureuser/ansible-project/setup_db.sql
      args:
        executable: /bin/bash

    - name: Copier index.php vers Apache
      copy:
        src: /home/azureuser/ansible-project/index.php
        dest: /var/www/html/index.php
        remote_src: yes

    - name: Copier admin.php vers Apache
      copy:
        src: /home/azureuser/ansible-project/admin.php
        dest: /var/www/html/admin.php
        remote_src: yes

    - name: Copier suivi.php vers Apache
      copy:
        src: /home/azureuser/ansible-project/suivi.php
        dest: /var/www/html/suivi.php
        remote_src: yes

    - name: Supprimer index.html par defaut
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Redemarrer Apache2
      service:
        name: apache2
        state: restarted
